[build]
  # 构建命令
  command = "npm run build"
  # 发布目录（静态文件所在位置）
  publish = "dist/spa"

[build.environment]
  # 设置Node.js版本
  NODE_VERSION = "18"

# 重定向规则（处理SPA路由）
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 安全头设置
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
